"""
This type stub file was generated by pyright.
"""

import base64
import contextlib
import dataclasses
import io
import logging
import os
import re
import time
import warnings
import adbutils
from functools import cached_property
from typing import Any, Dict, List, Optional, Tuple, Union
from lxml import etree
from PIL import Image
from retry import retry
from uiautomator2 import xpath
from uiautomator2._input import InputMethodMixIn
from uiautomator2._proto import Direction, HTTP_TIMEOUT, SCROLL_STEPS
from uiautomator2._selector import Selector, UiObject
from uiautomator2.abstract import AbstractShell, AbstractUiautomatorServer, ShellResponse
from uiautomator2.base import _BaseClient
from uiautomator2.exceptions import *
from uiautomator2.settings import Settings
from uiautomator2.swipe import SwipeExt
from uiautomator2.utils import deprecated, image_convert, list2cmdline
from uiautomator2.watcher import WatchContext, Watcher

WAIT_FOR_DEVICE_TIMEOUT = ...
logger = ...
def enable_pretty_logging(level=...): # -> None:
    ...

class _Device(_BaseClient):
    __orientation = ...
    def window_size(self): # -> tuple[int, int]:
        """ return (width, height) """
        ...
    
    def screenshot(self, filename: Optional[str] = ..., format=..., display_id: Optional[int] = ...): # -> Image | None:
        """
        Take screenshot of device

        Returns:
            PIL.Image.Image, np.ndarray (OpenCV format) or None

        Args:
            filename (str): saved filename, if filename is set then return None
            format (str): used when filename is empty. one of ["pillow", "opencv"]
            display_id (int): use specific display if device has multiple screen

        Examples:
            screenshot("saved.jpg")
            screenshot().save("saved.png")
            cv2.imwrite('saved.jpg', screenshot(format='opencv'))
        """
        ...
    
    def dump_hierarchy(self, compressed=..., pretty=..., max_depth: Optional[int] = ...) -> str:
        """
        Dump window hierarchy

        Args:
            compressed (bool): return compressed xml
            pretty (bool): pretty print xml
            max_depth (int): max depth of hierarchy

        Returns:
            xml content
        """
        ...
    
    def implicitly_wait(self, seconds: Optional[float] = ...) -> float:
        """set default wait timeout
        Args:
            seconds(float): to wait element show up

        Returns:
            Current implicitly wait seconds

        Deprecated:
            recommend use: d.settings['wait_timeout'] = 10
        """
        ...
    
    @property
    def pos_rel2abs(self): # -> Callable[..., tuple[int | Any, int | Any]]:
        """
        returns a function which can convert percent size to pixel size
        """
        ...
    
    @property
    def touch(self): # -> _Touch:
        """
        ACTION_DOWN: 0 ACTION_MOVE: 2
        touch.down(x, y)
        touch.move(x, y)
        touch.up(x, y)
        """
        class _Touch:
            ...
        
        
    
    def click(self, x: Union[float, int], y: Union[float, int]): # -> None:
        ...
    
    def double_click(self, x, y, duration=...): # -> None:
        """
        double click position
        """
        ...
    
    def long_click(self, x, y, duration: float = ...): # -> None:
        '''long click at arbitrary coordinates.
        
        Args:
            duration (float): seconds of pressed
        '''
        ...
    
    def swipe(self, fx, fy, tx, ty, duration: Optional[float] = ..., steps: Optional[int] = ...): # -> Any:
        """
        Args:
            fx, fy: from position
            tx, ty: to position
            duration (float): duration
            steps: 1 steps is about 5ms, if set, duration will be ignore

        Documents:
            uiautomator use steps instead of duration
            As the document say: Each step execution is throttled to 5ms per step.

        Links:
            https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#swipe%28int,%20int,%20int,%20int,%20int%29
        """
        ...
    
    def swipe_points(self, points: List[Tuple[int, int]], duration: float = ...): # -> Any:
        """
        Args:
            points: is point array containg at least one point object. eg [[200, 300], [210, 320]]
            duration: duration to inject between two points

        Links:
            https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html#swipe(android.graphics.Point[], int)
        """
        ...
    
    def drag(self, sx, sy, ex, ey, duration=...): # -> Any:
        '''Swipe from one point to another point.'''
        ...
    
    def press(self, key: Union[int, str], meta=...): # -> Any:
        """
        press key via name or key code. Supported key name includes:
            home, back, left, right, up, down, center, menu, search, enter,
            delete(or del), recent(recent apps), volume_up, volume_down,
            volume_mute, camera, power.
        """
        ...
    
    def long_press(self, key: Union[int, str]): # -> None:
        """
        long press key via name or key code

        Args:
            key: key name or key code
        
        Examples:
            long_press("home") same as "adb shell input keyevent --longpress KEYCODE_HOME"
        """
        ...
    
    def screen_on(self): # -> None:
        ...
    
    def screen_off(self): # -> None:
        ...
    
    @property
    def orientation(self) -> str:
        '''
        orienting the device to left/right or natural.
        left/l:       rotation=90 , displayRotation=1
        right/r:      rotation=270, displayRotation=3
        natural/n:    rotation=0  , displayRotation=0
        upsidedown/u: rotation=180, displayRotation=2
        '''
        ...
    
    @orientation.setter
    def orientation(self, value: str): # -> None:
        '''setter of orientation property.'''
        ...
    
    def freeze_rotation(self, freezed: bool = ...): # -> None:
        ...
    
    @property
    def last_traversed_text(self): # -> Any:
        '''get last traversed text. used in webview for highlighted text.'''
        ...
    
    def clear_traversed_text(self): # -> None:
        '''clear the last traversed text.'''
        ...
    
    @property
    def last_toast(self) -> Optional[str]:
        ...
    
    def clear_toast(self): # -> None:
        ...
    
    def open_notification(self): # -> Any:
        ...
    
    def open_quick_settings(self): # -> Any:
        ...
    
    def open_url(self, url: str): # -> None:
        ...
    
    def exists(self, **kwargs): # -> Exists:
        ...
    
    @property
    def clipboard(self) -> Optional[str]:
        ...
    
    @clipboard.setter
    def clipboard(self, text: str): # -> None:
        ...
    
    def set_clipboard(self, text, label=...): # -> None:
        '''
        Args:
            text: The actual text in the clip.
            label: User-visible label for the clip data.
        '''
        ...
    
    def clear_text(self): # -> None:
        """ clear input text """
        ...
    
    def send_keys(self, text: str): # -> None:
        """
        send text to focused input area
        
        Args:
            text: input text
            clear: clear text before input
        """
        ...
    
    def keyevent(self, v): # -> None:
        """
        Args:
            v: eg home wakeup back
        """
        ...
    
    @cached_property
    def serial(self) -> str:
        """
        If connected with USB, here should return self._serial
        When this situation happends

            d = u2.connect_usb("10.0.0.1:5555")
            d.serial # should be "10.0.0.1:5555"
            d.shell(['getprop', 'ro.serialno']).output.strip() # should uniq str like ffee123ca

        This logic should not change, because it used in tmq-service
        and if you break it, some people will not happy
        """
        ...
    
    def __call__(self, **kwargs) -> UiObject:
        ...
    


class _AppMixIn(AbstractShell):
    def session(self, package_name: str, attach: bool = ...) -> Session:
        """
        launch app and keep watching the app's state

        Args:
            package_name: package name
            attach: attach to existing session or not

        Returns:
            Session
        """
        ...
    
    def app_current(self): # -> dict[str, Any]:
        """
        Returns:
            dict(package, activity, pid?)

        Raises:
            DeviceError

        For developer:
            Function reset_uiautomator need this function, so can't use jsonrpc here.
        """
        ...
    
    def app_install(self, data: str): # -> None:
        """
        Install app

        Args:
            data: can be file path or url or file object
        """
        ...
    
    def wait_activity(self, activity, timeout=...) -> bool:
        """ wait activity
        Args:
            activity (str): name of activity
            timeout (float): max wait time

        Returns:
            bool of activity
        """
        ...
    
    def app_start(self, package_name: str, activity: Optional[str] = ..., wait: bool = ..., stop: bool = ..., use_monkey: bool = ...): # -> None:
        """ Launch application
        Args:
            package_name (str): package name
            activity (str): app activity
            stop (bool): Stop app before starting the activity. (require activity)
            use_monkey (bool): use monkey command to start app when activity is not given
            wait (bool): wait until app started. default False
        """
        ...
    
    def app_wait(self, package_name: str, timeout: float = ..., front=...) -> int:
        """ Wait until app launched
        Args:
            package_name (str): package name
            timeout (float): maxium wait time
            front (bool): wait until app is current app

        Returns:
            pid (int) 0 if launch failed
        """
        ...
    
    def app_list(self, filter: str = ...) -> List[str]:
        """
        List installed app package names

        Args:
            filter: [-f] [-d] [-e] [-s] [-3] [-i] [-u] [--user USER_ID] [FILTER]
        
        Returns:
            list of apps by filter
        """
        ...
    
    def app_list_running(self) -> List[str]:
        """
        Returns:
            list of running apps
        """
        ...
    
    def app_stop(self, package_name: str): # -> None:
        """ Stop one application """
        ...
    
    def app_stop_all(self, excludes=...): # -> list[str]:
        """ Stop all third party applications
        Args:
            excludes (list): apps that do now want to kill

        Returns:
            a list of killed apps
        """
        ...
    
    def app_clear(self, package_name: str): # -> None:
        """ Stop and clear app data: pm clear """
        ...
    
    def app_uninstall(self, package_name: str) -> bool:
        """ Uninstall an app 

        Returns:
            bool: success
        """
        ...
    
    def app_uninstall_all(self, excludes=..., verbose=...): # -> list[Any]:
        """ Uninstall all apps """
        ...
    
    def app_info(self, package_name: str) -> Dict[str, Any]:
        """
        Get app info

        Args:
            package_name (str): package name

        Return example:
            {
                "versionName": "1.1.7",
                "versionCode": 1001007
            }

        Raises:
            AppNotFoundError
        """
        ...
    
    def app_auto_grant_permissions(self, package_name: str): # -> None:
        """ auto grant permissions

        Args:
            package_name (str): package name
        
        Help of "adb shell pm":
            grant [--user USER_ID] PACKAGE PERMISSION
            revoke [--user USER_ID] PACKAGE PERMISSION
                These commands either grant or revoke permissions to apps.  The permissions
                must be declared as used in the app's manifest, be runtime permissions
                (protection level dangerous), and the app targeting SDK greater than Lollipop MR1 (API level 22).
        
        Help of "Android official pm" see <https://developer.android.com/tools/adb#pm>
            Grant a permission to an app. On devices running Android 6.0 (API level 23) and higher,
              the permission can be any permission declared in the app manifest.
            On devices running Android 5.1 (API level 22) and lower,
              must be an optional permission defined by the app.
        """
        ...
    


class _DeprecatedMixIn:
    @property
    def wait_timeout(self):
        ...
    
    @wait_timeout.setter
    def wait_timeout(self, v: Union[int, float]): # -> None:
        ...
    
    @property
    def click_post_delay(self):
        """ Deprecated or not deprecated, this is a question """
        ...
    
    @click_post_delay.setter
    def click_post_delay(self, v: Union[int, float]): # -> None:
        ...
    
    def unlock(self): # -> None:
        """ unlock screen with swipe from left-bottom to right-top """
        ...
    
    def show_float_window(self, show=...): # -> None:
        """ 显示悬浮窗，提高uiautomator运行的稳定性 """
        ...
    
    @deprecated(reason="use d.toast.show(text, duration) instead")
    def make_toast(self, text, duration=...):
        """ Show toast
        Args:
            text (str): text to show
            duration (float): seconds of display
        """
        ...
    
    @property
    def toast(self): # -> Toast:
        class Toast:
            ...
        
        
    
    def set_orientation(self, value: str): # -> None:
        '''setter of orientation property.'''
        ...
    


class _PluginMixIn:
    def watch_context(self, autostart: bool = ..., builtin: bool = ...) -> WatchContext:
        ...
    
    @cached_property
    def watcher(self) -> Watcher:
        ...
    
    @cached_property
    def xpath(self) -> xpath.XPathEntry:
        ...
    
    @cached_property
    def image(self): # -> ImageX:
        ...
    
    @cached_property
    def screenrecord(self): # -> Screenrecord:
        ...
    
    @cached_property
    def swipe_ext(self) -> SwipeExt:
        ...
    


class Device(_Device, _AppMixIn, _PluginMixIn, InputMethodMixIn, _DeprecatedMixIn):
    """ Device object """
    def clear_text(self): # -> None:
        """ clear input text """
        ...
    
    def send_keys(self, text: str, clear: bool = ...): # -> None:
        """
        send text to focused input area
        
        Args:
            text: input text
            clear: clear text before input
        """
        ...
    


class Session(Device):
    """Session keeps watch the app status
    each jsonrpc call will check if the package is still running
    """
    def __init__(self, dev: adbutils.AdbDevice, package_name: str) -> None:
        ...
    
    def running(self) -> bool:
        ...
    
    @property
    def pid(self) -> int:
        ...
    
    def jsonrpc_call(self, method: str, params: Any = ..., timeout: float = ...) -> Any:
        ...
    
    def restart(self): # -> None:
        """ restart app """
        ...
    
    def close(self): # -> None:
        """ close app """
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


def connect(serial: Union[str, adbutils.AdbDevice] = ...) -> Device:
    """
    Args:
        serial (str): Android device serialno

    Returns:
        Device

    Raises:
        ConnectError

    Example:
        connect("10.0.0.1:5555")
        connect("cff1123ea")  # adb device serial number
    """
    ...

def connect_usb(serial: Optional[str] = ...) -> Device:
    """
    Args:
        serial (str): android device serial

    Returns:
        Device

    Raises:
        ConnectError
    """
    ...

