"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Optional, Union
from uiautomator2.abstract import AbstractShell
from uiautomator2.utils import deprecated

"""Created on Wed May 22 2024 16:23:56 by codeskyblue
"""
logger = ...
@dataclass
class BroadcastResult:
    code: Optional[int]
    data: Optional[str]
    ...


BORADCAST_RESULT_OK = ...
BROADCAST_RESULT_CANCELED = ...
class InputMethodMixIn(AbstractShell):
    def set_input_ime(self, enable: bool = ...): # -> None:
        """ Enable of Disable InputIME """
        ...
    
    def is_input_ime_installed(self) -> bool:
        ...
    
    def send_keys(self, text: str): # -> Literal[True]:
        ...
    
    def send_action(self, code: Union[str, int] = ...): # -> None:
        """
        Simulate input method edito code

        Args:
            code (str or int): input method editor code

        Examples:
            send_action("search"), send_action(3)

        Refs:
            https://developer.android.com/reference/android/view/inputmethod/EditorInfo
        """
        ...
    
    def clear_text(self): # -> None:
        ...
    
    def current_ime(self) -> str:
        """ Current input method
        Returns:
            ime_method

        Example output:
            "com.github.uiautomator/.FastInputIME"
        """
        ...
    
    def hide_keyboard(self): # -> None:
        """ Hide keyboard """
        ...
    
    @deprecated(reason="use set_input_ime instead")
    def set_fastinput_ime(self, enable: bool = ...): # -> None:
        ...
    
    @deprecated(reason="use set_input_ime instead")
    def wait_fastinput_ime(self, timeout=...): # -> None:
        """ wait FastInputIME is ready (Depreacated in version 3.1) """
        ...
    


