"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple
from PIL import Image

class Selector(dict):
    """The class is to build parameters for UiSelector passed to Android device.
    """
    __fields = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def __str__(self) -> str:
        """ remove useless part for easily debugger """
        ...
    
    def __setitem__(self, k, v): # -> None:
        ...
    
    def __delitem__(self, k): # -> None:
        ...
    
    def clone(self): # -> Selector:
        ...
    
    def child(self, **kwargs): # -> Self:
        ...
    
    def sibling(self, **kwargs): # -> Self:
        ...
    
    def update_instance(self, i): # -> None:
        ...
    


class UiObject:
    def __init__(self, session, selector: Selector) -> None:
        ...
    
    @property
    def wait_timeout(self):
        ...
    
    @property
    def exists(self): # -> Exists:
        '''check if the object exists in current window.'''
        ...
    
    @property
    def info(self):
        '''ui object info.'''
        ...
    
    def screenshot(self, display_id: Optional[int] = ...) -> Image.Image:
        ...
    
    def click(self, timeout=..., offset=...): # -> None:
        """
        Click UI element. 

        Args:
            timeout: seconds wait element show up
            offset: (xoff, yoff) default (0.5, 0.5) -> center

        The click method does the same logic as java uiautomator does.
        1. waitForExists 2. get VisibleBounds center 3. send click event

        Raises:
            UiObjectNotFoundError
        """
        ...
    
    def bounds(self) -> Tuple[int, int, int, int]:
        """
        Returns:
            left_top_x, left_top_y, right_bottom_x, right_bottom_y
        """
        ...
    
    def center(self, offset=...): # -> tuple[float | Any, float | Any]:
        """
        Args:
            offset: optional, (x_off, y_off)
                (0, 0) means left-top, (0.5, 0.5) means middle(Default)
        Return:
            center point (x, y)
        """
        ...
    
    def click_gone(self, maxretry=..., interval=...): # -> bool:
        """
        Click until element is gone

        Args:
            maxretry (int): max click times
            interval (float): sleep time between clicks

        Return:
            Bool if element is gone
        """
        ...
    
    def click_exists(self, timeout=...) -> bool:
        ...
    
    def long_click(self, duration: float = ..., timeout=...):
        """
        Args:
            duration (float): seconds of pressed
            timeout (float): seconds wait element show up
        """
        ...
    
    def drag_to(self, *args, **kwargs):
        ...
    
    def swipe(self, direction, steps=...): # -> None:
        """
        Performs the swipe action on the UiObject.
        Swipe from center

        Args:
            direction (str): one of ("left", "right", "up", "down")
            steps (int): move steps, one step is about 5ms
            percent: float between [0, 1]

        Note: percent require API >= 18
        # assert 0 <= percent <= 1
        """
        ...
    
    def gesture(self, start1, start2, end1, end2, steps=...):
        '''
        perform two point gesture.
        Usage:
        d().gesture(startPoint1, startPoint2, endPoint1, endPoint2, steps)
        '''
        ...
    
    def pinch_in(self, percent=..., steps=...):
        ...
    
    def pinch_out(self, percent=..., steps=...):
        ...
    
    def wait(self, exists=..., timeout=...): # -> bool:
        """
        Wait until UI Element exists or gone

        Args:
            timeout (float): wait element timeout

        Example:
            d(text="Clock").wait()
            d(text="Settings").wait(exists=False) # wait until it's gone
        """
        ...
    
    def wait_gone(self, timeout=...): # -> bool:
        """ wait until ui gone
        Args:
            timeout (float): wait element gone timeout

        Returns:
            bool if element gone
        """
        ...
    
    def must_wait(self, exists=..., timeout=...): # -> None:
        """ wait and if not found raise UiObjectNotFoundError """
        ...
    
    def send_keys(self, text):
        """ alias of set_text """
        ...
    
    def set_text(self, text, timeout=...):
        ...
    
    def get_text(self, timeout=...):
        """ get text from field """
        ...
    
    def clear_text(self, timeout=...):
        ...
    
    def child(self, **kwargs): # -> UiObject:
        ...
    
    def sibling(self, **kwargs): # -> UiObject:
        ...
    
    def child_by_text(self, txt, **kwargs): # -> UiObject:
        ...
    
    def child_by_description(self, txt, **kwargs): # -> UiObject:
        ...
    
    def child_by_instance(self, inst, **kwargs): # -> UiObject:
        ...
    
    def parent(self):
        ...
    
    def __getitem__(self, instance: int): # -> UiObject:
        """
        Raises:
            IndexError
        """
        ...
    
    @property
    def count(self):
        ...
    
    def __len__(self):
        ...
    
    def __iter__(self): # -> Iter:
        class Iter:
            ...
        
        
    
    def right(self, **kwargs): # -> UiObject | None:
        ...
    
    def left(self, **kwargs): # -> UiObject | None:
        ...
    
    def up(self, **kwargs): # -> UiObject | None:
        ...
    
    def down(self, **kwargs): # -> UiObject | None:
        ...
    
    @property
    def fling(self): # -> _Fling:
        """
        Args:
            dimention (str): one of "vert", "vertically", "vertical", "horiz", "horizental", "horizentally"
            action (str): one of "forward", "backward", "toBeginning", "toEnd", "to"
        """
        class _Fling:
            ...
        
        
    
    @property
    def scroll(self): # -> _Scroll:
        """
        Args:
            dimention (str): one of "vert", "vertically", "vertical", "horiz", "horizental", "horizentally"
            action (str): one of "forward", "backward", "toBeginning", "toEnd", "to"
        """
        class _Scroll:
            ...
        
        
    


