"""
This type stub file was generated by pyright.
"""

import abc
import typing
import adbutils
from typing import Any, List, NamedTuple, Tuple, Union
from PIL import Image
from uiautomator2._proto import Direction

"""Created on Thu Apr 25 2024 15:08:43 by codeskyblue
"""
class ShellResponse(NamedTuple):
    output: str
    exit_code: int
    ...


class AbstractUiautomatorServer(abc.ABC):
    @abc.abstractmethod
    def start_uiautomator(self): # -> None:
        ...
    
    @abc.abstractmethod
    def stop_uiautomator(self): # -> None:
        ...
    
    @abc.abstractmethod
    def jsonrpc_call(self, method: str, params: Any = ...) -> Any:
        ...
    


class AbstractShell(abc.ABC):
    @abc.abstractmethod
    def shell(self, cmdargs: Union[List[str], str]) -> ShellResponse:
        ...
    
    @property
    @abc.abstractmethod
    def adb_device(self) -> adbutils.AdbDevice:
        ...
    
    @property
    @abc.abstractmethod
    def jsonrpc(self) -> typing.Any:
        ...
    


class AbstractXPathBasedDevice(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def click(self, x: int, y: int): # -> None:
        ...
    
    @abc.abstractmethod
    def long_click(self, x: int, y: int): # -> None:
        ...
    
    @abc.abstractmethod
    def send_keys(self, text: str): # -> None:
        ...
    
    @abc.abstractmethod
    def swipe(self, fx: int, fy: int, tx: int, ty: int, duration: float): # -> None:
        """ duration is float type, indicate seconds """
        ...
    
    @abc.abstractmethod
    def swipe_ext(self, direction: Direction, scale: float): # -> None:
        ...
    
    @abc.abstractmethod
    def window_size(self) -> Tuple[int, int]:
        """ return (width, height) """
        ...
    
    @abc.abstractmethod
    def dump_hierarchy(self) -> str:
        """ return xml content """
        ...
    
    @abc.abstractmethod
    def screenshot(self) -> Image.Image:
        """ return PIL.Image.Image """
        ...
    


