"""
This type stub file was generated by pyright.
"""

import adbutils
from functools import cached_property
from typing import Any, Dict, List, Optional, Union
from uiautomator2.abstract import ShellResponse
from uiautomator2.core import BasicUiautomatorServer
from uiautomator2.exceptions import *
from uiautomator2.settings import Settings

logger = ...
class _BaseClient(BasicUiautomatorServer):
    """
    提供最基础的控制类，这个类暂时先不公开吧
    """
    def __init__(self, serial: Optional[Union[str, adbutils.AdbDevice]] = ...) -> None:
        """
        Args:
            serial: device serialno
        """
        ...
    
    @property
    def adb_device(self) -> adbutils.AdbDevice:
        ...
    
    @cached_property
    def settings(self) -> Settings:
        ...
    
    def sleep(self, seconds: float): # -> None:
        """ same as time.sleep """
        ...
    
    def shell(self, cmdargs: Union[str, List[str]], timeout=...) -> ShellResponse:
        """
        Run shell command on device

        Args:
            cmdargs: str or list, example: "ls -l" or ["ls", "-l"]
            timeout: seconds of command run, works on when stream is False

        Returns:
            ShellResponse

        Raises:
            AdbShellError
        """
        ...
    
    @property
    def info(self) -> Dict[str, Any]:
        ...
    
    @property
    def device_info(self) -> Dict[str, Any]:
        ...
    
    @property
    def wlan_ip(self) -> Optional[str]:
        ...
    
    @property
    def jsonrpc(self): # -> JSONRpcWrapper:
        class JSONRpcWrapper:
            ...
        
        
    
    def reset_uiautomator(self): # -> None:
        """
        restart uiautomator service

        Orders:
            - stop uiautomator keeper
            - am force-stop com.github.uiautomator
            - start uiautomator keeper(am instrument -w ...)
            - wait until uiautomator service is ready
        """
        ...
    
    def push(self, src, dst: str, mode=...): # -> None:
        """
        Push file into device

        Args:
            src (path or fileobj): source file
            dst (str): destination can be folder or file path
            mode (int): file mode
        """
        ...
    
    def pull(self, src: str, dst: str): # -> None:
        """
        Pull file from device to local
        """
        ...
    


