"""
This type stub file was generated by pyright.
"""

import adbutils
from http.client import HTTPConnection
from typing import Any, Optional
from uiautomator2.abstract import AbstractUiautomatorServer

"""Created on Thu Apr 25 2024 14:50:05 by codeskyblue
"""
logger = ...
class MockAdbProcess:
    def __init__(self, conn: adbutils.AdbConnection) -> None:
        ...
    
    @property
    def output(self) -> bytes:
        """ subprocess do not have this property """
        ...
    
    def wait(self) -> bool:
        ...
    
    def pool(self) -> Optional[int]:
        ...
    
    def kill(self): # -> None:
        ...
    


def launch_uiautomator(dev: adbutils.AdbDevice) -> MockAdbProcess:
    """Launch uiautomator2 server on device"""
    ...

class HTTPResponse:
    def __init__(self, content: bytes) -> None:
        ...
    
    def json(self): # -> Any:
        ...
    
    @property
    def text(self): # -> str:
        ...
    


class AdbHTTPConnection(HTTPConnection):
    def __init__(self, device: adbutils.AdbDevice, port=...) -> None:
        ...
    
    def connect(self): # -> None:
        ...
    
    def __enter__(self) -> HTTPConnection:
        ...
    
    def __exit__(self, exc_type, exc_value, traceback): # -> None:
        ...
    


class BasicUiautomatorServer(AbstractUiautomatorServer):
    """ Simple uiautomator2 server client
    this is runs without atx-agent
    """
    _lock = ...
    def __init__(self, dev: adbutils.AdbDevice, device_server_port: int = ...) -> None:
        ...
    
    @property
    def debug(self) -> bool:
        ...
    
    @debug.setter
    def debug(self, value: bool): # -> None:
        ...
    
    def start_uiautomator(self): # -> None:
        """
        Start uiautomator2 server

        Raises:
            LaunchUiautomatorError: uiautomator2 server not ready
        """
        ...
    
    def stop_uiautomator(self, wait=...): # -> None:
        ...
    
    def jsonrpc_call(self, method: str, params: Any = ..., timeout: float = ...) -> Any:
        """Send jsonrpc call to uiautomator2 server"""
        ...
    


