"""
This type stub file was generated by pyright.
"""

class BaseException(Exception):
    """ base error for uiautomator2 """
    ...


class DeviceError(BaseException):
    ...


class AdbShellError(DeviceError):
    ...


class ConnectError(DeviceError):
    ...


class HTTPError(DeviceError):
    ...


class HTTPTimeoutError(HTTPError):
    ...


class AdbBroadcastError(DeviceError):
    ...


class UiAutomationError(DeviceError):
    ...


class InputIMEError(DeviceError):
    ...


class UiAutomationNotConnectedError(UiAutomationError):
    ...


class InjectPermissionError(UiAutomationError):
    ...


class APKSignatureError(UiAutomationError):
    ...


class LaunchUiAutomationError(UiAutomationError):
    ...


class AccessibilityServiceAlreadyRegisteredError(UiAutomationError):
    ...


class RPCError(BaseException):
    ...


class RPCUnknownError(RPCError):
    ...


class RPCInvalidError(RPCError):
    ...


class HierarchyEmptyError(RPCError):
    ...


class RPCStackOverflowError(RPCError):
    ...


class NormalError(RPCError):
    ...


class XPathElementNotFoundError(NormalError):
    ...


class SessionBrokenError(NormalError):
    ...


class UiObjectNotFoundError(NormalError):
    ...


class AppNotFoundError(NormalError):
    ...


