"""
This type stub file was generated by pyright.
"""

import typing
import numpy as np
import uiautomator2
from typing import Union
from PIL import Image

ImageType = typing.Union[np.ndarray, Image.Image]
compare_ssim = ...
logger = ...
def color_bgr2gray(image: ImageType): # -> Image:
    """ change color image to gray
    Returns:
        opencv-image
    """
    ...

def template_ssim(image_a: ImageType, image_b: ImageType):
    """
    Refs:
        https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_template_matching/py_template_matching.html
    """
    ...

def cv2crop(im: np.ndarray, bounds: tuple = ...):
    ...

def compare_ssim(image_a: ImageType, image_b: ImageType, full=..., bounds=...):
    ...

def compare_ssim_debug(image_a: ImageType, image_b: ImageType, color=...):
    """
    Args:
        image_a, image_b: opencv image or PIL.Image
        color: (r, g, b) eg: (255, 0, 0) for red

    Refs:
        https://www.pyimagesearch.com/2017/06/19/image-difference-with-opencv-and-python/
    """
    ...

def show_image(im: Union[np.ndarray, Image.Image]): # -> None:
    ...

def pil2cv(pil_image) -> np.ndarray:
    """ Convert from pillow image to opencv """
    ...

def pil2base64(pil_image, format=...) -> str:
    """ Convert pillow image to base64 """
    ...

def cv2pil(cv_image): # -> Image:
    """ Convert opencv to pillow image """
    ...

def iscv2(im): # -> bool:
    ...

def ispil(im): # -> bool:
    ...

def conv2cv(im: Union[np.ndarray, Image.Image]) -> np.ndarray:
    ...

def conv2pil(im: Union[np.ndarray, Image.Image]) -> Image.Image:
    ...

def draw_point(im: Image.Image, x: int, y: int) -> Image.Image:
    """
    Mark position to show which point clicked

    Args:
        im: pillow.Image
    """
    ...

def imread(data) -> np.ndarray:
    """
    Args:
        data: local path or http url or data:image/base64,xxx
    
    Returns:
        opencv image
    
    Raises:
        IOError
    """
    ...

class ImageX:
    def __init__(self, d: uiautomator2.Device) -> None:
        """
        Args:
            d (uiautomator2 instance)
        """
        ...
    
    def send_click(self, x, y): # -> None:
        ...
    
    def getpixel(self, x, y): # -> float | tuple[int, ...] | None:
        """
        Returns:
            (r, g, b)
        """
        ...
    
    def match(self, imdata: Union[np.ndarray, str, Image.Image]): # -> dict[str, Any | list[Any]]:
        """
        Args:
            imdata: file, url, pillow or opencv image object
        
        Returns:
            templateMatch result
        """
        ...
    
    def wait(self, imdata, timeout=..., threshold=...): # -> dict[str, Any | list[Any]] | None:
        """ wait until image show up """
        ...
    
    def click(self, imdata, timeout=..., threshold=...): # -> None:
        """
        Args:
            imdata: file, url, pillow or opencv image object
        """
        ...
    


if __name__ == "__main__":
    ...
