"""
This type stub file was generated by pyright.
"""

import uiautomator2 as u2

def iter_image_from_minicap(uri): # -> Generator[Any, Any, Never]:
    ...

class Screenrecord:
    def __init__(self, d: u2.Device) -> None:
        ...
    
    def __call__(self, *args, **kwargs): # -> Self:
        ...
    
    def stop(self): # -> bool:
        """
        stop record and finish write video
        Returns:
            bool: whether video is recorded.
        """
        ...
    


