"""
This type stub file was generated by pyright.
"""

from typing import Any

logger = ...
class Settings:
    """ 赋值时会检查类型 """
    def __init__(self, d) -> None:
        ...
    
    def get(self, key: str) -> Any:
        ...
    
    def __setitem__(self, key: str, val: Any): # -> None:
        ...
    
    def __getitem__(self, key: str) -> Any:
        ...
    
    def __repr__(self): # -> str:
        ...
    


