"""
This type stub file was generated by pyright.
"""

from typing import Optional, Tuple, Union
from ._proto import Direction

class SwipeExt:
    def __init__(self, d) -> None:
        """
        Args：
            d (uiautomator2.Device)
        """
        ...
    
    def __call__(self, direction: Union[Direction, str], scale: float = ..., box: Optional[Tuple[int, int, int, int]] = ..., **kwargs): # -> None:
        """
        Args:
            direction (str): one of "left", "right", "up", "bottom" or Direction.LEFT
            scale (float): percent of swipe, range (0, 1.0]
            box (tuple): None or [lx, ly, rx, ry]
            kwargs: used as kwargs in d.swipe

        Raises:
            ValueError
        """
        ...
    


