"""
This type stub file was generated by pyright.
"""

import contextlib
import pathlib
import typing
from typing import Tuple, Union
from PIL import Image
from uiautomator2._proto import Direction

@contextlib.contextmanager
def with_package_resource(filename: str) -> typing.Generator[pathlib.Path, None, None]:
    """
    Context manager to access a package asset file using importlib.resources.
    
    Args:
        filename (str): The name of the file to locate.
    
    Yields:
        str: The full path to the located file.
    """
    ...

def check_alive(fn): # -> _Wrapped[..., Any, ..., Any]:
    ...

_cached_values = ...
def cache_return(fn): # -> _Wrapped[..., Any, ..., Any]:
    ...

def hooks_wrap(fn): # -> _Wrapped[..., Any, ..., None]:
    ...

def wrap_wait_exists(fn): # -> _Wrapped[..., Any, ..., Any]:
    ...

def intersect(rect1, rect2): # -> tuple[Any, Any, Any, Any]:
    ...

class Exists:
    """Exists object with magic methods."""
    def __init__(self, uiobject) -> None:
        ...
    
    def __nonzero__(self):
        """Magic method for bool(self) python2 """
        ...
    
    def __bool__(self):
        """ Magic method for bool(self) python3 """
        ...
    
    def __call__(self, timeout=...): # -> bool:
        """Magic method for self(args).

        Args:
            timeout (float): exists in seconds
        """
        ...
    
    def __repr__(self): # -> str:
        ...
    


def list2cmdline(args: Union[str, list, tuple]) -> str:
    ...

def inject_call(fn, *args, **kwargs): # -> object:
    """
    Call function without known all the arguments

    Args:
        fn: function
        args: arguments
        kwargs: key-values
    
    Returns:
        as the fn returns
    """
    ...

def natualsize(size: int) -> str:
    ...

def swipe_in_bounds(d: uiautomator2.Device, bounds: Tuple[int, int, int, int], direction: Union[Direction, str], scale: float = ...): # -> None:
    """
    Args:
        d: Device object
        bounds: list of [lx, ly, rx, ry]
        direction: one of ["left", "right", "up", "down"]
        scale: percent of swipe, range (0, 1.0)
    
    Raises:
        AssertionError, ValueError
    """
    ...

def thread_safe_wrapper(fn: typing.Callable): # -> _Wrapped[..., Any, ..., Any]:
    ...

def is_version_compatiable(expect_version: str, actual_version: str) -> bool:
    """
    Check if the actual version is compatiable with the expect version

    Args:
        expect_version: expect version, e.g. 1.0.0
        actual_version: actual version, e.g. 1.0.0

    Returns:
        bool: True if compatiable, otherwise False
    """
    ...

def deprecated(reason): # -> Callable[..., _Wrapped[..., Any, ..., Any]]:
    ...

def image_convert(im: Image.Image, format: str): # -> Image:
    ...

