"""
This type stub file was generated by pyright.
"""

import typing
import uiautomator2
from typing import Optional
from uiautomator2.xpath import PageSource

logger = ...
class WatchContext:
    def __init__(self, d: uiautomator2.Device, builtin: bool = ...) -> None:
        ...
    
    def wait_stable(self, seconds: float = ..., timeout: float = ...): # -> Literal[True]:
        """ wait until watches not triggered
        Args:
            seconds: stable seconds
            timeout: raise error when wait stable timeout

        Raises:
            TimeoutError
        """
        ...
    
    def when(self, xpath: str): # -> Self:
        """ 当条件满足时,支持 .when(..).when(..) 的级联模式"""
        ...
    
    def call(self, fn: typing.Callable): # -> None:
        """
        Args:
            fn: support args (d: Device, el: Element)
                see _run_callback function for more details
        """
        ...
    
    def click(self): # -> None:
        ...
    
    def start(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def close(self): # -> None:
        """ alias of stop """
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, type, value, traceback): # -> None:
        ...
    


class Watcher:
    def __init__(self, d: uiautomator2.Device) -> None:
        ...
    
    def when(self, xpath=...): # -> XPathWatcher:
        ...
    
    def start(self, interval: float = ...): # -> Thread | None:
        """ stop watcher """
        ...
    
    def stop(self): # -> None:
        """ stop watcher """
        ...
    
    def reset(self): # -> None:
        """ stop watching and remove all watchers """
        ...
    
    def running(self) -> bool:
        ...
    
    @property
    def triggering(self) -> bool:
        ...
    
    def run(self, source: Optional[PageSource] = ...): # -> bool:
        """ run watchers
        Args:
            source: hierarchy content
        """
        ...
    
    def __call__(self, name: str) -> XPathWatcher:
        ...
    
    def remove(self, name=...): # -> None:
        """ remove watcher """
        ...
    


class XPathWatcher:
    def __init__(self, parent: Watcher, xpath: str, name: str = ...) -> None:
        ...
    
    def when(self, xpath: str = ...): # -> Self:
        ...
    
    def call(self, func: callable): # -> None:
        """
        func accept argument, key(d, el)
        d=self._d, el=element
        """
        ...
    
    def click(self): # -> None:
        ...
    
    def press(self, key): # -> None:
        """
        key (str): on of
            ("home", "back", "left", "right", "up", "down", "center",
            "search", "enter", "delete", "del", "recent", "volume_up",
            "menu", "volume_down", "volume_mute", "camera", "power")
        """
        ...
    


